backend:
  name: git-gateway
  branch: decap-cms # Branch to update (optional; defaults to master)

media_folder: "src/content/posts/images" # Location where files will be stored in the repo
public_folder: "./images" # The src attribute for uploaded media

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "src/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime",  format: "LLL"}
      - { label: "Thumbnail", name: "image", widget: "image"}
      - { label: "Category", name: "category", widget: "string", required: false}
      - { label: "Author", name: "author", widget: "string", required: false}
      - { label: "Featured", name: "featured", widget: "boolean"}
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }